version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    ports:
      - "${SERVER_PORT:-4000}:4000"
    env_file:
      - ./packages/server/.env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app/packages/server
    command: yarn dev