version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "${SERVER_PORT:-4000}:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    # volumes:
      # - .:/app
      # - /app/node_modules
    # command: yarn dev