version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    expose:
      - "4000"  # Only expose internally to Nginx Proxy Manager
    env_file:
      - .env
    environment:
      - NODE_ENV=production

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"        # HTTP
      - "443:443"      # HTTPS
      - "81:81"        # Admin UI
    volumes:
      - ./docker/volumes/data/nginx/data:/data
      - ./docker/volumes/data/nginx/letsencrypt:/etc/letsencrypt